baseURL = '/'
languageCode = 'en-us'
title = 'Dedham Food Pantry'
theme = 'mainroad'

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[markup.goldmark.renderHooks]
[markup.goldmark.renderHooks.link]
# This tells Hugo to "capture" resources using ".Get".  If I don't use
# this, then page resources don't get processed by the pipeline so
# they don't get copied from the page bundle to the public directory.
# I'm not sure why this "default" isn't enabled by default.
# https://gohugo.io/render-hooks/links/#default
enableDefault = true

[Params]
description = "The Dedham Food Pantry provides food at no cost to qualifying Dedham residents."
customCSS = ["css/dfp.css"]
googleFontsLink = false

[Params.logo]
image = "logo-no-text.jpg"
altText = "The Dedham Food Pantry logo which is three full grocery bags on a red-and-white checked tablecloth."
subtitle = "Neighbors Helping Neighbors"

[menus]
  [[menus.main]]
    name = 'Need Help?'
    pageRef = '/help/'
    weight = 1
  [[menus.main]]
    name = 'Please Donate'
    pageRef = '/donate/'
    weight = 2
  [[menus.main]]
    name = 'Please Volunteer'
    pageRef = '/volunteer/'
    weight = 3
  [[menus.main]]
    name = 'About Us'
    pageRef = '/about/'
    weight = 4
  [[menus.main]]
    name = 'Contact Us'
    pageRef = '/contact/'
    weight = 5
